import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Header } from '@/components/layout/Header';
import { Main } from '@/components/layout/Main';
import { Sidebar } from '@/components/layout/Sidebar';
import { Suspense } from 'react';
import { ProfileMenu } from '@/components/layout/ProfileMenu';
import { ProfileMenuProvider } from '@/contexts/profile-menu.context';
import { SidebarProvider } from '@/contexts/sidebar.context';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: {
    default: 'GTasks',
    template: '%s | GTasks',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ProfileMenuProvider>
          <SidebarProvider>
            <div className="flex min-h-screen">
              <Sidebar className="fixed left-0 top-0 h-screen w-screen md:w-48" />
              <div className="md:ml-48 flex flex-1 flex-col">
                <Header />
                <Suspense>
                  <Main className="flex-1 overflow-y-auto">{children}</Main>
                </Suspense>
              </div>
              <ProfileMenu />
            </div>
          </SidebarProvider>
        </ProfileMenuProvider>
      </body>
    </html>
  );
}
