import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Header } from '@/components/layout/Header';
import { Main } from '@/components/layout/Main';
import { Sidebar } from '@/components/layout/Sidebar';
import { Container } from '@/components/Container';
import { Suspense } from 'react';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: {
    default: 'GTasks',
    template: '%s | GTasks',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Container className="flex min-h-screen">
          <Sidebar className="hidden md:block fixed left-0 top-0 h-screen w-56" />
          <Container className="md:ml-56 flex flex-1 flex-col">
            <Header />
            <Suspense>
              <Main className="flex-1 overflow-y-auto">{children}</Main>
            </Suspense>
          </Container>
        </Container>
      </body>
    </html>
  );
}
