import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Header } from '@/components/layout/Header';
import { Main } from '@/components/layout/Main';
import { Sidebar } from '@/components/layout/Sidebar';
import { Container } from '@/components/Container';
import { Suspense } from 'react';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: {
    default: 'GTasks',
    template: '%s | GTasks',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Container className="md:flex">
          <Sidebar className="hidden md:flex md:flex-1" />
          <Container className="md:flex-6 lg:flex-7">
            <Header />
            <Suspense>
              <Main>{children}</Main>
            </Suspense>
          </Container>
        </Container>
      </body>
    </html>
  );
}
